### ISSUE TITLE
"Open Pull Request" command error

### ISSUE THREAD

**Issue by stilliard** [Microsoft/vscode-github-issues-prs#35]
Hey, awesome extension btw!

Minor issue, but I'm getting the following error when I run "Open Pull Request" from the command palette:
```
Running the contributed command:'githubIssuesPrs.openPullRequest' failed.
```

Full log output:
```
[2018-06-05 14:52:52.583] [exthost1] [error] TypeError: Cannot read property 'item' of undefined
	at GitHubIssuesPrsProvider.openIssue (/home/andrew/.vscode/extensions/ms-vscode.github-issues-prs-0.9.0/out/src/github-issues-prs.js:299:81)
	at e._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:636:704)
	at e.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:637:141)
	at e._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:599:737)
	at e._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:599:455)
	at e._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:598:529)
	at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:598:298)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:597:226
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:600:324
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:88:119
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:89:496)
	at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:145:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20) githubIssuesPrs.openPullRequest
```

I've filled in my github.username & the sidebar list of issues & pull requests works perfectly.
I'm on ubuntu 18.04 if that helps with any debugging.
Thank you.

**Comment by chrmarti** [comment]
I need to hide the commands from the command palette. They need an issue/PR as their argument which they only get when run from the tree view in the Explorer.

**Comment by dps999** [comment]
I have the same on Mac
